.TH sixarm-debian-sysop-packages 1 "2010-09-10" "SixArm.com" "http://sixarm.com" 
.SH NAME 
sixarm-debian-sysop-packages \- systems operator packages we like to use together

.SH SYNOPSIS
.B sixarm-debian-sysop-packages

.SH DESCRIPTION
System Operator packages we like to use together.

.SH BUGS
To report a bug, please send email to sixarm@sixarm.com

.SH AUTHORS
.TP
.B Joel Parker Henderson at SixArm.com
.I http://sixarm.com
